<?php
error_reporting(0);
set_time_limit(0);

// Default
$defaultPath = realpath(dirname(__FILE__)) . '/';

$base = isset($_GET['path']) && $_GET['path'] !== '' ? rtrim($_GET['path'], '/') . '/' : $defaultPath;

echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Domain Grabber</title>
<style>
body { background: #000; color: #0f0; font-family: monospace; padding: 20px; }
a { color: #0ff; text-decoration: none; }
a:hover { text-decoration: underline; color: #fff; }
h1 { color: #f0f; }
button, input[type='submit'] { background: #111; color: #0f0; padding: 8px 16px; border: 1px solid #0f0; cursor: pointer; margin-top: 10px; }
button:hover, input[type='submit']:hover { background: #0f0; color: #000; }
input[type='text'] {
    background: #111; color: #0f0; border: 1px solid #0f0; padding: 6px; width: 400px;
}
form { margin-bottom: 20px; }
</style>
<script>
function copyLinks() {
    const links = Array.from(document.querySelectorAll('.link')).map(a => a.href).join('\\n');
    navigator.clipboard.writeText(links).then(() => {
        alert('✅ Semua link berhasil disalin!');
    });
}
</script>
</head><body>";

echo "<h1>Domain Grabber</h1><hr>";

// Form input
echo "<form method='GET'>
<label>📂 Path Folder: </label><br>
<input type='text' name='path' placeholder='Contoh: /home/user/domains/' value='".htmlspecialchars($base, ENT_QUOTES)."'>
<input type='submit' value='🔍 Scan'>
</form>";

if (!is_dir($base)) {
    echo "<p>❌ Folder path tidak ditemukan: <b>$base</b></p></body></html>";
    exit;
}

$dirs = scandir($base);
$domains = [];

foreach ($dirs as $d) {
    if ($d !== '.' && $d !== '..' && is_dir($base . $d)) {
//filter
        if (preg_match('/^([a-z0-9-]+\.)+[a-z]{2,}$/i', $d)) {
            $domains[] = "http://$d/";
        }
    }
}

echo "<p>✅ Total: <b>" . count($domains) . "</b> domain valid ditemukan dari: <code>$base</code></p>";
echo "<button onclick='copyLinks()'>📋 Copy Semua Link</button>";
echo "<ul>";

foreach ($domains as $url) {
    echo "<li><a class='link' href='{$url}' target='_blank'>{$url}</a></li>";
}

echo "</ul><hr><p style='color:#888'>🔥 Generated by <b>0x6ick</b> @ ".date("H:i:s")."</p></body></html>";
?>